# Generated by Django 4.1.4 on 2023-02-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
