# Generated by Django 4.1.4 on 2023-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employeedetails_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('dept_size', models.IntegerField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
    ]
